### ISSUE TITLE
get build fixes upstream

### ISSUE THREAD

**Issue by dvj** [hunter-packages/libzmq#1]
@fwinnen Do you know if any effort has been made to get the compile fixes pushed upsteam? It seems like the differences are fairly minor, and it would be great to be able to keep pace with recent zmq releases

Thanks for your efforts!

**Comment by fwinnen** [comment]
I don’t know of any effort made.
But yeah, its a hassle to keep merging changes when packets update…

**Comment by ruslo** [comment]
Closing inactive discussion.
